name: Vercel Report Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/lat-client/CHANGELOG.md'

jobs:
  vercel-lat-client:
    runs-on: ubuntu-latest
    name: "Deploying report to Vercel"
    steps:
      - run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
